/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LtgPosCaller */

#ifndef _Included_LtgPosCaller
#define _Included_LtgPosCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LtgPosCaller
 * Method:    ltgPosition
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_LtgPosCaller_ltgPosition
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LtgPosCaller
 * Method:    mallocResBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LtgPosCaller_mallocResBytes
  (JNIEnv *, jobject);

/*
 * Class:     LtgPosCaller
 * Method:    freeResBytes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LtgPosCaller_freeResBytes
  (JNIEnv *, jobject);

/*
 * Class:     LtgPosCaller
 * Method:    setCfg
 * Signature: (IIDDZ)V
 */
JNIEXPORT void JNICALL Java_LtgPosCaller_setCfg
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jboolean);

/*
 * Class:     LtgPosCaller
 * Method:    setCfgFromFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LtgPosCaller_setCfgFromFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
