# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tmsg.proto\"\xaa\x03\n\rmsg_to_server\x12\'\n\x07msgType\x18\x01 \x02(\x0e\x32\x16.msg_to_server.MSGTYPE\x12\x0c\n\x04size\x18\x02 \x02(\x05\x12\x10\n\x08msgIndex\x18\x03 \x02(\x05\x12&\n\x05_init\x18\x04 \x01(\x0b\x32\x17.msg_to_server.INIT_msg\x12#\n\x03\x63\x61l\x18\x05 \x01(\x0b\x32\x16.msg_to_server.CAL_msg\x12#\n\x03\x65nd\x18\x06 \x01(\x0b\x32\x16.msg_to_server.END_msg\x1a}\n\x08INIT_msg\x12\x13\n\x0bn_of_sensor\x18\x01 \x02(\x05\x12\r\n\x05is_3D\x18\x02 \x02(\x05\x12\x12\n\nfirst_diff\x18\x03 \x01(\x01\x12\x13\n\x0bsecond_diff\x18\x04 \x01(\x01\x12\x11\n\tsearchDom\x18\x05 \x03(\x01\x12\x11\n\tsensorLoc\x18\x06 \x03(\x01\x1a\x1d\n\x07\x43\x41L_msg\x12\x12\n\nsensorTime\x18\x01 \x03(\x01\x1a\x19\n\x07\x45ND_msg\x12\x0e\n\x06is_END\x18\x01 \x02(\x05\"%\n\x07MSGTYPE\x12\x08\n\x04INIT\x10\x00\x12\x07\n\x03\x43\x41L\x10\x01\x12\x07\n\x03\x45ND\x10\x02\"k\n\x17search_result_to_client\x12\x10\n\x08msgIndex\x18\x01 \x02(\x05\x12\x0c\n\x04size\x18\x02 \x02(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\x01\x12\x0c\n\x04time\x18\x04 \x01(\x01\x12\x13\n\x0bresults_xyz\x18\x05 \x03(\x01'
)



_MSG_TO_SERVER_MSGTYPE = _descriptor.EnumDescriptor(
  name='MSGTYPE',
  full_name='msg_to_server.MSGTYPE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='END', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=403,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_MSG_TO_SERVER_MSGTYPE)


_MSG_TO_SERVER_INIT_MSG = _descriptor.Descriptor(
  name='INIT_msg',
  full_name='msg_to_server.INIT_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='n_of_sensor', full_name='msg_to_server.INIT_msg.n_of_sensor', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_3D', full_name='msg_to_server.INIT_msg.is_3D', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_diff', full_name='msg_to_server.INIT_msg.first_diff', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='second_diff', full_name='msg_to_server.INIT_msg.second_diff', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchDom', full_name='msg_to_server.INIT_msg.searchDom', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorLoc', full_name='msg_to_server.INIT_msg.sensorLoc', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=343,
)

_MSG_TO_SERVER_CAL_MSG = _descriptor.Descriptor(
  name='CAL_msg',
  full_name='msg_to_server.CAL_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorTime', full_name='msg_to_server.CAL_msg.sensorTime', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=374,
)

_MSG_TO_SERVER_END_MSG = _descriptor.Descriptor(
  name='END_msg',
  full_name='msg_to_server.END_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_END', full_name='msg_to_server.END_msg.is_END', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=401,
)

_MSG_TO_SERVER = _descriptor.Descriptor(
  name='msg_to_server',
  full_name='msg_to_server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgType', full_name='msg_to_server.msgType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='msg_to_server.size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgIndex', full_name='msg_to_server.msgIndex', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_init', full_name='msg_to_server._init', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cal', full_name='msg_to_server.cal', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='msg_to_server.end', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MSG_TO_SERVER_INIT_MSG, _MSG_TO_SERVER_CAL_MSG, _MSG_TO_SERVER_END_MSG, ],
  enum_types=[
    _MSG_TO_SERVER_MSGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=440,
)


_SEARCH_RESULT_TO_CLIENT = _descriptor.Descriptor(
  name='search_result_to_client',
  full_name='search_result_to_client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgIndex', full_name='search_result_to_client.msgIndex', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='search_result_to_client.size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='search_result_to_client.error', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='search_result_to_client.time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='results_xyz', full_name='search_result_to_client.results_xyz', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=549,
)

_MSG_TO_SERVER_INIT_MSG.containing_type = _MSG_TO_SERVER
_MSG_TO_SERVER_CAL_MSG.containing_type = _MSG_TO_SERVER
_MSG_TO_SERVER_END_MSG.containing_type = _MSG_TO_SERVER
_MSG_TO_SERVER.fields_by_name['msgType'].enum_type = _MSG_TO_SERVER_MSGTYPE
_MSG_TO_SERVER.fields_by_name['_init'].message_type = _MSG_TO_SERVER_INIT_MSG
_MSG_TO_SERVER.fields_by_name['cal'].message_type = _MSG_TO_SERVER_CAL_MSG
_MSG_TO_SERVER.fields_by_name['end'].message_type = _MSG_TO_SERVER_END_MSG
_MSG_TO_SERVER_MSGTYPE.containing_type = _MSG_TO_SERVER
DESCRIPTOR.message_types_by_name['msg_to_server'] = _MSG_TO_SERVER
DESCRIPTOR.message_types_by_name['search_result_to_client'] = _SEARCH_RESULT_TO_CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msg_to_server = _reflection.GeneratedProtocolMessageType('msg_to_server', (_message.Message,), {

  'INIT_msg' : _reflection.GeneratedProtocolMessageType('INIT_msg', (_message.Message,), {
    'DESCRIPTOR' : _MSG_TO_SERVER_INIT_MSG,
    '__module__' : 'msg_pb2'
    # @@protoc_insertion_point(class_scope:msg_to_server.INIT_msg)
    })
  ,

  'CAL_msg' : _reflection.GeneratedProtocolMessageType('CAL_msg', (_message.Message,), {
    'DESCRIPTOR' : _MSG_TO_SERVER_CAL_MSG,
    '__module__' : 'msg_pb2'
    # @@protoc_insertion_point(class_scope:msg_to_server.CAL_msg)
    })
  ,

  'END_msg' : _reflection.GeneratedProtocolMessageType('END_msg', (_message.Message,), {
    'DESCRIPTOR' : _MSG_TO_SERVER_END_MSG,
    '__module__' : 'msg_pb2'
    # @@protoc_insertion_point(class_scope:msg_to_server.END_msg)
    })
  ,
  'DESCRIPTOR' : _MSG_TO_SERVER,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg_to_server)
  })
_sym_db.RegisterMessage(msg_to_server)
_sym_db.RegisterMessage(msg_to_server.INIT_msg)
_sym_db.RegisterMessage(msg_to_server.CAL_msg)
_sym_db.RegisterMessage(msg_to_server.END_msg)

search_result_to_client = _reflection.GeneratedProtocolMessageType('search_result_to_client', (_message.Message,), {
  'DESCRIPTOR' : _SEARCH_RESULT_TO_CLIENT,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:search_result_to_client)
  })
_sym_db.RegisterMessage(search_result_to_client)


# @@protoc_insertion_point(module_scope)
